### ISSUE TITLE
init-presentation

### ISSUE THREAD

**Issue by essarraj-fouad** [labs-web/gestion-projet#35]
# Init présentation

## Travail à faire 
Création d'une présentation sans contenu, mais avec les titres des diapositives
## Livrable 
- backlog/sous-tâche/2.init-presentation.35.md
- docs/_layouts/presentation.html
- docs/conclusion/conclusion.md
- docs/introduction/introduction.md
- docs/index.md
- docs/presentation.md
- docs/rapport.md
- README.md
- README.json

**Comment by husseinbouik** [comment]
le pullrequest a une conflit

**Comment by zaani12** [comment]
Livrable non valide
